-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS Styles
(
    style_id integer NOT NULL DEFAULT nextval('"Dance"."Styles_style_id_seq"'::regclass),
    name character varying(30) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT "Styles_pkey" PRIMARY KEY (style_id),
    CONSTRAINT name UNIQUE (name)
);

CREATE TABLE IF NOT EXISTS user
(
    user_id integer NOT NULL DEFAULT nextval('"Dance".user_user_id_seq'::regclass),
    login character varying(20) COLLATE pg_catalog."default" NOT NULL,
    passwd character varying(100) COLLATE pg_catalog."default" NOT NULL,
    email character varying(100) COLLATE pg_catalog."default" NOT NULL,
    avatar bytea,
    time_user timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT user_pkey PRIMARY KEY (user_id),
    CONSTRAINT user_email_key UNIQUE (email),
    CONSTRAINT user_login_key UNIQUE (login)
);

CREATE TABLE IF NOT EXISTS saved_publication
(
    publication_id integer NOT NULL,
    user_id integer NOT NULL,
    time_like timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT saved_publication_pkey PRIMARY KEY (publication_id, user_id)
);

CREATE TABLE IF NOT EXISTS publications
(
    publication_id integer NOT NULL DEFAULT nextval('"Dance".publications_publication_id_seq'::regclass),
    description text COLLATE pg_catalog."default",
    dance text COLLATE pg_catalog."default" NOT NULL,
    style_id integer,
    CONSTRAINT publications_pkey PRIMARY KEY (publication_id),
    CONSTRAINT dance UNIQUE (dance)
);

CREATE TABLE IF NOT EXISTS publication_and_user
(
    user_id integer NOT NULL,
    publication_id integer NOT NULL,
    time_of_public timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT publication_and_user_pkey PRIMARY KEY (user_id, publication_id)
);

CREATE TABLE IF NOT EXISTS Comments
(
    comment_id serial,
    user_id integer NOT NULL,
    publication_id integer NOT NULL,
    time_comment timestamp without time zone DEFAULT current_timestamp,
    PRIMARY KEY (id_comment)
);

ALTER TABLE IF EXISTS saved_publication
    ADD FOREIGN KEY (publication_id)
    REFERENCES "Dance".publications (publication_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS saved_publication
    ADD FOREIGN KEY (user_id)
    REFERENCES "Dance"."user" (user_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS publications
    ADD FOREIGN KEY (style_id)
    REFERENCES "Dance"."Styles" (style_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS publication_and_user
    ADD FOREIGN KEY (user_id)
    REFERENCES "Dance"."user" (user_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS publication_and_user
    ADD FOREIGN KEY (publication_id)
    REFERENCES "Dance".publications (publication_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS Comments
    ADD FOREIGN KEY (user_id)
    REFERENCES "Dance"."user" (user_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS Comments
    ADD FOREIGN KEY (publication_id)
    REFERENCES "Dance".publications (publication_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;
